/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,html}"],
  theme: {
    extend: {
      colors: {
        crumb: {
          dark: "#121212",
          secondary: "#252525",
          accent: "#FF8C00",
          textPrimary: "#EBEBEB",
          textSecondary: "#A0A0A0",
          error: "#FF3B30",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        skate_light: {
          "base-100": "#FAFAFA",
          "base-200": "#F5F0F0",
          "base-300": "#EAE0E0",
          "base-content": "#1A1111",
          primary: "#8B1A1A", 
          "primary-content": "#FFFFFF",
          accent: "#7A1616",
          "accent-content": "#FFFFFF",
          neutral: "#1A1111",
          "neutral-content": "#F9FAFB",
          info: "#3B82F6",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#EF4444",
        },
      },
      {
        skate_dark: {
          "base-100": "#110C0C",
          "base-200": "#1C1313",
          "base-300": "#2C1C1C",
          "base-content": "#F3E8E8",
          primary: "#8B1A1A",
          "primary-content": "#FFFFFF",
          accent: "#7A1616",
          "accent-content": "#FFFFFF",
          neutral: "#1A1111",
          "neutral-content": "#D4C4C4",
          info: "#38BDF8",
          success: "#34D399",
          warning: "#FBBF24",
          error: "#F87171",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
